surf/urls.py
from django.urls import path

from surf.views import SurfReportHomeView
from . import views

app_name = 'surf'

urlpatterns = [
    path('', SurfReportHomeView().view, name='home'),
    path('<int:pk>/', views.SurfReportDetailView().view, name='surf_report'),
    path('<int:pk>/tag/add', views.AddTagView().view, name='add_tag'),
    path('tag/<int:pk>', views.ShowTagView().view, name='show_tag'),
    path('tag/new', views.CreateTagView().view, name='new_tag'),
    path('report/fetch', views.FetchReportView().view, name='fetch_report'),
    path('search', views.SearchView().view, name='search'),
    path('api/surf_reports', views.ApiSurfResults().view, name='api_surf_reports'),
]

surf_conditions/urls.py
from django.urls import include, path

urlpatterns = [
    path('', include('surf.urls')),
]

surf/models.py
import random

from django.db import models

from surf.managers import SurfReportQuerySet


class Tag(models.Model):
    label = models.CharField(max_length=30, unique=True)


class SurfReport(models.Model):
    captured_at = models.DateTimeField()
    local_time = models.DateTimeField()
    min_swell = models.FloatField()
    max_swell = models.FloatField()
    tags = models.ManyToManyField(Tag)
    note = models.TextField(max_length=150)

    objects = SurfReportQuerySet.as_manager()

    class Meta:
        indexes = [
            models.Index(fields=['-captured_at']),
            models.Index(fields=['note']),
        ]


class Note:
    words = ['folly', 'fun', 'times', 'cow', 'sheep', 'hello', 'weeee', 'holiday', 'lollipop', 'bird', 'run', 'seek',
             'climb', 'swim', 'crawl', 'sunshine', 'moon', 'the', 'a', 'fresh', 'food', 'fish', 'table', 'coffee',
             'pooky', 'egg', 'taco', 'maths', 'science', 'planet', 'star', 'bag', 'sat', 'on', 'medicine', 'tray',
             'sleep', 'blanket', 'cord', 'carpet', 'dear', 'love', 'regards', 'thanks', 'sorry', 'sure', 'see', 'you',
             'I', 'soon', 'run', 'running', 'dinosaur', 'did-you-think-he-saw-us-rex', 'saw', 'flute']

    @classmethod
    def generate(cls):
        return ' '.join([random.choice(cls.words) for i in range(10)])

surf/forms.py
from django import forms


class TagForm(forms.Form):
    label = forms.CharField(label='Tag label', max_length=30)

    label.widget.attrs.update({'autofocus': 'autofocus', 'placeholder': 'tag name'})


class SearchForm(forms.Form):
    query = forms.CharField(label='Query', min_length=3)

    query.widget.attrs.update({'autofocus': 'autofocus', 'placeholder': 'search text'})

surf/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.core.paginator import Paginator
from django.core.cache import cache

from surf import settings
from surf.forms import TagForm, SearchForm
from surf.models import SurfReport, Tag
from surf.services import SurfReportGateway, FetchService


class SurfReportHomeView:
    def view(self, request):
        all_reports = SurfReport.objects.all().fetch_tags().order_by_captured_at()
        reports = Paginator(all_reports, 15).get_page(request.GET.get('page'))

        context = {
            'latest': reports[0] if reports else None,
            'reports': reports,
        }

        return render(request, 'surf/home.html', context)


class SurfReportDetailView:
    def view(self, request, **url_params):
        surf_report = get_object_or_404(SurfReport, pk=url_params['pk'])

        context = {
            'surf_report': surf_report,
            'tags': surf_report.tags.all(),
            'all_tags': Tag.objects.all(),
        }
        return render(request, 'surf/surf_report.html', context)


class CreateTagView:
    def view(self, request):
        if request.method == 'POST':
            form = TagForm(request.POST)

            if form.is_valid():
                Tag.objects.get_or_create(label=form.cleaned_data['label'])
                return HttpResponseRedirect(reverse('surf:home'))
        else:
            form = TagForm()

        return render(request, 'surf/new_tag.html', {'form': form})


class ShowTagView:
    def view(self, request, **url_params):
        tag = get_object_or_404(Tag, pk=url_params['pk'])
        reports = SurfReport.objects.prefetch_related('tags').filter(tags=tag).order_by('-captured_at')

        context = {
            'tag': tag,
            'reports': reports,
        }
        return render(request, 'surf/show_tag.html', context)


class AddTagView:
    def view(self, request, **url_params):
        surf_report = get_object_or_404(SurfReport, pk=url_params['pk'])
        tag = get_object_or_404(Tag, pk=request.POST['tag'])

        surf_report.tags.add(tag)
        surf_report.save()
        return HttpResponseRedirect(reverse('surf:home'))


class FetchReportView:
    def __init__(self, gateway=SurfReportGateway()):
        self.gateway = gateway

    def view(self, request):
        if request.method == 'POST':
            report = self.gateway.latest_report()
            report.save()

        return HttpResponseRedirect(reverse('surf:home'))


class SearchView:

    def __init__(self, results_per_page=settings.SEARCH_RESULTS_PER_PAGE):
        self.results_per_page = results_per_page

    def view(self, request):
        query = request.GET.get('query')
        results = SurfReport.objects.fetch_tags().search(query)
        pages = Paginator(results, self.results_per_page)

        context = {
            'form': SearchForm(request.GET) if query else SearchForm(),
            'num_of_results': SurfReport.objects.search(query).count(),
            'results': pages.get_page(request.GET.get('page')),
            'query_params': {'query': query} if query else None,
            'search_term': query,
        }

        return render(request, 'surf/search.html', context)


class ApiSurfResults:

    def __init__(self, fetch_service=FetchService()):
        self.fetch_service = fetch_service

    def url_to_page(self, request, page):
        uri = request.build_absolute_uri(reverse('surf:api_surf_reports'))
        return '%s?page=%d' % (uri, page)

    def conditional_link(self, name, uri):
        return {name: uri} if uri else {}

    def view(self, request):
        reports, served_from_cache = self.fetch_service.load_page(request.GET.get('page', '1'))

        body_content = {
            'surf_reports': [{
                'id': report.id,
                'captured_at': report.captured_at.isoformat(),
                'min_swell': round(report.min_swell, 2),
                'max_swell': round(report.max_swell, 2),
                'tags': [tag.label for tag in report.tags.all()],
                'note': report.note,
            } for report in reports.results],
            'metadata': {
                'page': reports.page,
                'number_of_pages': reports.num_pages,
                'served_from_cache': served_from_cache,
            },
            'links': {
                'home': request.build_absolute_uri(reverse('surf:home')),
                **(self.conditional_link('previous_page', reports.has_previous() and self.url_to_page(request, reports.previous_page()))),
                **(self.conditional_link('next_page', reports.has_next() and self.url_to_page(request, reports.next_page()))),
                **(self.conditional_link('first_page', reports.has_previous() and self.url_to_page(request, 1))),
                **(self.conditional_link('last_page', reports.has_next() and self.url_to_page(request, reports.num_pages))),
            },
        }

        return JsonResponse(body_content)

surf/templates/surf/frame.html
{% load static %}

<html lang="en">
    <head>
        <link rel='stylesheet' type='text/css' href="{% static 'surf/style.css' %}" />
        <title>Surf Report</title>
    </head>
    <body>
        <div class='page_frame'>
            <div class='navigation_menu'>
                <div class='site_title'>Surf Conditions</div>

                <ul class='menu'>
                    <li class='menu_item'><a href="{% url 'surf:home' %}">Home</a></li>
                    <li class='menu_item'><a href="{% url 'surf:new_tag' %}">Add tag</a></li>
                    <li class='menu_item'><a href="{% url 'surf:search' %}">Search</a></li>
                    <li class='menu_item'><a href="{% url 'surf:api_surf_reports' %}">Api</a></li>
                    <li class='menu_item'>
                        <form action="{% url 'surf:fetch_report' %}" method='post' class='fetch_report_menu_item'>
                            {% csrf_token %}
                            <input type='submit' value='Fetch report' class='submit_fetch_report' />
                        </form>
                    </li>
                </ul>
            </div>

            <h2 class='page_title'>{% block title %}{% endblock %}</h2>

            <div class='content'>{% block content %}{% endblock %}</div>
        </div>

        <script async src="{% static 'surf/script.js' %}"></script>
    </body>
</html>

surf/templates/surf/home.html
{% extends "./frame.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <h4>Latest conditions</h4>
    {% if latest %}
        <div class='latest_surf_report'>
            <div class='swell'>Current swell is {{latest.min_swell|floatformat:2}}m to {{latest.max_swell|floatformat:2}}m.</div>
            <div class='tags'>
                {% for tag in latest.tags.all %}
                    <a href="{% url 'surf:show_tag' tag.id %}" class='tag'>{{tag.label}}</a>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <div class='no_surf_reports'>There are no surf reports, conditions unknown.</div>
    {% endif %}

    {% if reports %}
        <h4 class='previous-header'>Previous conditions</h4>

        {% include 'surf/partials/tabular_reports.html' with reports=reports only %}
    {% endif %}
{% endblock %}

surf/templates/surf/index.html
{% load static %}
{% load humanize %}

<html lang="en">
    <head>
        <link rel='stylesheet' type='text/css' href="{% static 'surf/style.css' %}" />
        <title>Surf Report</title>
    </head>
    <body>
        <h2>Surf Reports</h2>

        <div class='latest_surf_report'>
            <p class='swell'>Current swell is {{latest.min_swell}}m to {{latest.max_swell}}m.</p>
        </div>

        {% if more_reports %}
            <table class='more_reports'>
                <thead>
                    <th>Index</th>
                    <th>Captured at</th>
                    <th class='swell'>Swell From (m)</th>
                    <th class='swell'>Swell To (m)</th>
                </thead>
                {% for report in more_reports %}
                    <tr class="{% cycle 'row_a' 'row_b' %}">
                        <td>{{forloop.counter}}</td>
                        <td>{{report.captured_at|naturaltime}}</td>
                        <td class='swell'>{{latest.min_swell}}</td>
                        <td class='swell'>{{latest.max_swell}}</td>
                    </tr>
                {% endfor %}
            </table>
        {% endif %}

        <script async src="{% static 'surf/script.js' %}"></script>
    </body>
</html>

surf/templates/surf/latest-report.html
{% load static %}

<html>
    <head>
        <link rel='stylesheet' type='text/css' href="{% static 'surf/style.css' %}" />
        <title>Surf Report</title>
    </head>
    <body>
        <h2>Latest Surf Report</h2>

        <div class='surf_report'>
            <p class='captured_at'>The report was captured at {{surf_report.captured_at|date:'r'}}</p>
            <p class='swell'>Swell from {{surf_report.min_swell}}m to {{surf_report.max_swell}}m.</p>
        </div>

        <script async src="{% static 'surf/script.js' %}"></script>
    </body>
</html>

surf/templates/surf/new_tag.html
{% extends "./frame.html" %}

{% block title %}New tag{% endblock %}

{% block content %}
    <form action="{% url 'surf:new_tag' %}" method='post'>
        {% csrf_token %}
        {{form}}
        <input type='submit' value='Create' />
    </form>
{% endblock %}}

surf/templates/surf/partials/tabular_reports.html
{% load humanize %}
{% load surf_templatetags %}

<table class='more_reports'>
    <thead>
        <th>Index</th>
        <th>Id</th>
        <th>Captured at</th>
        <th class='swell'>Swell From</th>
        <th class='swell'>Swell To</th>
        <th class='tag'>Tags</th>
    </thead>

    {% for report in reports %}
        <tr class="{% cycle 'row_a' 'row_b' %}" data-url="{% url 'surf:surf_report' report.id %}">
            <td>{{forloop.counter}}</td>
            <td>{{report.id}}</td>
            <td>{{report.captured_at|naturaltime}}</td>
            <td class='swell'>{{report.min_swell|floatformat:2}}m</td>
            <td class='swell'>{{report.max_swell|floatformat:2}}m</td>
            <td class='tags'>
                {% for tag in report.tags.all %}
                    <a href="{% url 'surf:show_tag' tag.id %}" class='tag'>{{tag.label}}</a>
                {% endfor %}
            </td>
        </tr>
    {% endfor %}
</table>

{% if reports.has_previous or reports.has_next %}
    <div class='pagination'>
        {% if reports.has_previous %}
            <div class='previous_page'>
                <a href='{% query_params inherited_qp page=1 %}'>&laquo; first</a>
                <a href='{% query_params inherited_qp page=reports.previous_page_number %}'>&lsaquo; previous</a>
            </div>
        {% endif %}

        <div class='current_page'>Page {{reports.number}} of {{reports.paginator.num_pages}}</div>

        {% if reports.has_next %}
            <div class='next_page'>
                <a href='{% query_params inherited_qp page=reports.next_page_number %}'>next &rsaquo;</a>
                <a href='{% query_params inherited_qp page=reports.paginator.num_pages %}'>last &raquo;</a>
            </div>
        {% endif %}
    </div>
{% endif %}

surf/templates/surf/search.html
{% extends "./frame.html" %}

{% block title %}Search{% endblock %}

{% block content %}
    <h4>Search</h4>

    <form action="{% url 'surf:search' %}" method='get'>
        {{form}}
        <input type='submit' value='Search' />
    </form>

    {% if search_term %}
        <h4 class='search-results'>Search results</h4>

        <div class='result-count'>{{num_of_results}} results found.</div>
    {% endif %}

    {% if results %}
        {% include 'surf/partials/tabular_reports.html' with inherited_qp=query_params reports=results only %}
    {% endif %}

{% endblock %}

surf/templates/surf/show_tag.html
{% extends "./frame.html" %}

{% block title %}{{tag.label}}{% endblock %}

{% block content %}
    <h4>Surf reports</h4>

    {% if reports %}
        {% include 'surf/partials/tabular_reports.html' with reports=reports only %}
    {% else %}
        No reports.
    {% endif %}
{% endblock %}

surf/templates/surf/surf_report.html
{% extends "./frame.html" %}
{% load humanize %}

{% block title %}Surf Report {{surf_report.id}}{% endblock %}

{% block content %}
    <div class='surf_report_details'>
        <div class='at_time'>{{surf_report.captured_at|date:'r'}} ({{surf_report.captured_at|naturaltime}})</div>
        <div class='swell'>Swell was {{surf_report.min_swell}}m to {{surf_report.max_swell}}m.</div>
        <div class='notes'>{{surf_report.note}}</div>
        <div class='tags'>
            {% for tag in tags %}
                <a href="{% url 'surf:show_tag' tag.id %}" class='tag'>{{tag.label}}</a>
            {% endfor %}
        </div>
    </div>

    <div class='add_tags'>
        <form action="{% url 'surf:add_tag' surf_report.id %}" method='post'>
            {% csrf_token %}
            <label>
                Tag
                <select name='tag'>
                    {% for tag in all_tags %}
                        <option value="{{tag.id}}">{{tag.label}}</option>
                    {% endfor %}
                </select>
            </label>
            <input type='submit' value='Add tag' />
        </form>
    </div>
{% endblock %}